### ISSUE TITLE
Locations are not resolved by the unit registry via scope

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.registry#19]
e.g. this is used in the dal-visual-remote for resolving units via scope.

By entering a location scope in the unit scope field no units are resolved even with a valid location scope.

**Comment by pLeminoq** [comment]
Fixed by openbase/dal@85280fc58fdfe2aac97821b866969c85f51d6de6. The problem was not that the registry could not resolve the location by its scope but that the dal-visual-remote would check for a unitType in the scope first, which is not there for locations.
