### ISSUE TITLE
Change the registry structure so that everything is a unit

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.registry#2]
Since Locations, Devices, Agents, Scenes, ... are all units the registries and underlying data types should be modified in the following ways:

- The UnitConfig type should contain a oneof field which contains a message with additional information for that type (e.g if the unit type is SCENE than the oneof field should contain a SceneConfig). Thus in the message put in the oneof field, fields which are already dealt with by the UnitConfig have to be removed (e.g. scope in the SceneConfig). Also the EnablingState should be added to the UnitConfig.
- Then the registries have to move from their current data types to UnitConfigs (e.g SceneRegistry from SceneConfig to UnitConfig)

**Comment by DivineThreepwood** [comment]
Implemented and already integrated in paramite release.
