### ISSUE TITLE
Location - ConnectionId not registered in TileConfig of Location

### ISSUE THREAD

**Issue by TimoMichi** [openbase/bco.registry#25]
The TileId is registered in ConnectionConfig but not the other way around.

For consistency the ConnectionId should be registered in TileConfig.

**Comment by pLeminoq** [comment]
Why is this needed for consistency? If both ways are registered isn't that just redundant information we should try to avoid?

**Comment by DivineThreepwood** [comment]
yes, but it's just a id reference which should be ok.
The locations are referring there included units in the same way.
And the information is needed here for e.g. agents to discover their environment without resolving all the connection-location relations each time.
