### ISSUE TITLE
Unit Group Registry Version Upgrade fix.

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.registry#35]
Please fix the version converter to support a proper version upgrade inclusive unit groups.

<pre>
14:24:59.604 [main] ERROR o.o.j.p.Launcher     ╠══╦═⚀ Could not launch UnitRegistryLauncher!
14:24:59.604 [main] ERROR o.o.j.p.Launcher     ║  ╚══╦═⚀ org.openbase.jul.exception.CouldNotPerformException: Could not launch UnitRegistry
14:24:59.604 [main] ERROR o.o.j.p.Launcher     ║     ╚══╦═⚀ Could not launch UnitRegistry
14:24:59.604 [main] ERROR o.o.j.p.Launcher     ║        ╚══╦═⚀ Could not initialize class org.openbase.bco.registry.unit.core.UnitRegistryController!
14:24:59.604 [main] ERROR o.o.j.p.Launcher     ║           ╚══╦═⚀ Could not initialize class org.openbase.bco.registry.unit.core.UnitRegistryController!
14:24:59.604 [main] ERROR o.o.j.p.Launcher     ║              ╚══╦═⚀ Could not initialize class org.openbase.bco.registry.unit.core.UnitRegistryController!
14:24:59.604 [main] ERROR o.o.j.p.Launcher     ║                 ╚══╦═⚀ Could not load all internal registries!
14:24:59.604 [main] ERROR o.o.j.p.Launcher     ║                    ╚══╦═⚄ Could not load all registry entries!
14:24:59.605 [main] ERROR o.o.j.p.Launcher     ║                       ╠══╦═⚀ Could not instantiate FileSynchronizer!
14:24:59.605 [main] ERROR o.o.j.p.Launcher     ║                       ║  ╚══╦═⚀ Could not deserialize /home/julian/Dev/lsp-csra-ha-paramite/var/bco/registry/db/unit-group-config-db/70926b9f-916d-4718-9328-5f98bab5e8f2.json into rst.domotic.unit.UnitConfigType$UnitConfig$Builder@4115387!
14:24:59.605 [main] ERROR o.o.j.p.Launcher     ║                       ║     ╚════⚀ 24:25: Expected identifier. -}
14:24:59.605 [main] ERROR o.o.j.p.Launcher     ║                       ╚══╦═⚀ Could not instantiate FileSynchronizer!
14:24:59.605 [main] ERROR o.o.j.p.Launcher     ║                          ╚══╦═⚀ Could not deserialize /home/julian/Dev/lsp-csra-ha-paramite/var/bco/registry/db/unit-group-config-db/2c95255e-a491-46d7-a6a6-f66d5e6c2d3b.json into rst.domotic.unit.UnitConfigType$UnitConfig$Builder@2a350b4d!
14:24:59.605 [main] ERROR o.o.j.p.Launcher     ║                             ╚════⚀ 27:25: Expected identifier. -}
</pre>

**Comment by pLeminoq** [comment]
The version converter worked just fine but the whole upgrading process did also load the symlink unit-group-db as a database. Because this db was stored after the unit-group-config-db changes by the converter would be overwritten. Fixed by commit:

openbase/jul@aa79ef89fd6a21952184273d009018412f3d33d7
