### ISSUE TITLE
Register TransformationFrameId consistency handler for UnitGroups

### ISSUE THREAD

**Issue by THuppke** [openbase/bco.registry#41]
At 3rd of July, the TransformationFrameId consistency handlers for UnitGroups were not registered anywhere. Thus groups with positions but without TransformationFrameId could be created. Maybe has been fixed already.

**Comment by DivineThreepwood** [comment]
Was fixed in the bco.registry last Wednesday and  is already merged into the master branch.

**Comment by DivineThreepwood** [comment]
Feedback is welcome!
