### ISSUE TITLE
VirtualRegistrySyncTest sometimes failes during travlis builds: RootLocation is not available.

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.registry#50]
Tests in error: 
  VirtualRegistrySyncTest.testVirtualRegistrySync:263 » Execution org.openbase.j...

In my view this seems to be an internal registry controller sync problem. Because the root location is prevously registeredy through the LocationRegistryController: 
`ROOT_LOCATION = locationRegistry.registerLocationConfig(UnitConfig.newBuilder().setLabel(ROOT_LOCATION_LABEL).setType(UnitType.LOCATION).setLocationConfig(rootLocationConfig).build()).get();`

Maybe the registerLocationConfig method of the LocationRegistryController must make sure the internal unit remote registry is synced before the future returns the get method. If this is the case all controller and remote controller methods should implement this.

Here is the detailed log:

<pre>
Running org.openbase.bco.registry.unit.test.VirtualRegistrySyncTest
18:16:46.625 [main] INFO  o.o.j.p.JPTestMode Test mode enabled!
18:16:46.626 [main] INFO  o.o.j.p.JPVerbose Verbose is enabled!
18:16:46.626 [main] INFO  o.o.j.p.JPDebugMode Debug mode enabled!
18:16:46.702 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[43b75fc3-82d7-4f75-9d49-b6c3ffbfe66b]...
18:16:46.702 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[0b349066-0024-4fda-b42f-f54419eaebfb]...
18:16:46.702 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[20a67217-d324-4bfb-ad62-39f7dfe99533]...
18:16:46.711 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[e9228aa9-a8b6-4510-bd44-b55c5efbdf8c]...
18:16:46.711 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[444b325d-335a-43dd-a9dd-f31c8ce7548a]...
18:16:46.711 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[302218aa-85f4-4b5b-8c80-e65fce1e4b94]...
18:16:46.711 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[b238c22a-2dd9-44e8-a36a-3242a94f3fd1]...
18:16:46.712 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[77ec77a8-16c2-4209-ad64-31e98400be47]...
18:16:46.712 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[736977a6-4a6b-417b-846d-eac6d1d4c4ad]...
18:16:46.712 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[e157ae02-3d5e-4b1f-bfd2-383b17b2a339]...
18:16:46.712 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[d93d0710-3169-4940-b047-6cf5a848a859]...
18:16:46.712 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[617276d1-f656-4e50-8512-0c36ef33eb9e]...
18:16:46.713 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[e580667f-be9e-4832-bbdf-3f2310d974dc]...
18:16:46.713 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[5907bb60-19b6-4ff7-89b0-b050873d8173]...
18:16:46.713 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[1859992a-b634-461c-8c05-c86475ba9530]...
18:16:46.714 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[f6ec4f44-a849-42e9-b73b-28d03dd20e83]...
18:16:46.714 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[bfae7fb2-dc63-435b-bbb2-e7d94bc27507]...
18:16:46.714 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[059cf08b-530a-4708-aa5b-d85a1488ce85]...
18:16:46.723 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[148404de-6716-40c6-9c12-9526dbc352e1]...
18:16:46.723 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[0b789695-942d-4679-b599-592bacab6ead]...
18:16:46.723 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[2b125ddc-b0f5-41e3-aa15-d6097bb1d2a4]...
18:16:46.724 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[b5e1d063-1b4c-43de-a7b3-5373ae9f61a9]...
18:16:46.735 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[860f275d-2a70-4b30-8434-b7d4eeb777c1]...
18:16:46.735 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[3cd4d640-7496-43aa-83f3-a1cc5413cf60]...
18:16:46.736 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[6f1f4a8f-7632-4f94-86a4-5d64253b3647]...
18:16:46.736 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[e50a984c-3e72-4e3c-956d-2120458656c3]...
18:16:46.736 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[4733dc5e-d481-4413-891a-baa029b5f81e]...
18:16:46.737 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[5ddc95d5-d66d-4866-a6b0-927f3c72e515]...
18:16:46.737 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[269d4cf7-480f-498f-8313-e51d83b469ee]...
18:16:46.738 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[271566dd-458a-4f72-bec3-e3fcaebabf6f]...
18:16:46.738 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[fba6224a-9386-4fdc-8a0c-874496d19db2]...
18:16:46.791 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register ServiceTemplate[6b184212-0cf0-45be-a9a5-85164c62c742]...
18:16:46.795 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[2ef1896a-5876-4e98-9c22-c385714871c2]...
18:16:46.827 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[5851ca37-c554-46f1-b3a3-aeb249d13e3b]...
18:16:46.827 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[067e3e65-a963-4891-8c15-ce9f17084618]...
18:16:46.831 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[4a08e27e-2670-4844-8ab9-ea98f07c5692]...
18:16:46.839 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[2803ad14-04e0-48e4-9700-b709325baac2]...
18:16:46.839 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[e80e5822-b87b-4da6-ac7b-84c991fa5604]...
18:16:46.839 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[e3828d43-dd8a-4900-bd59-4d399ac7e4dc]...
18:16:46.840 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[a9e4ad31-4379-45e5-962c-35903a670927]...
18:16:46.840 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[bb6e148b-9568-4426-a850-0b6a574f4f8d]...
18:16:46.840 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[13496643-c521-4295-af86-8a78fc578f10]...
18:16:46.841 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[bb4d4415-e2fb-48ac-ae3b-8ac0a9e85199]...
18:16:46.841 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[c05a8534-7323-4f42-b581-d86f4469b44b]...
18:16:46.841 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[4f17a21c-793e-4b13-8d2a-6b6488976bc5]...
18:16:46.842 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[4ceb232a-d418-4dee-b3ea-83d3071ebc70]...
18:16:46.842 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[cf124a1c-07e8-4a55-bc76-fbd9796f9c1c]...
18:16:46.842 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[406f440e-7046-4b84-ac34-91f481ec3cd9]...
18:16:46.847 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[bca60d44-25c2-4428-99f7-df7a369c3dcf]...
18:16:46.853 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[0d4dc5b6-1da7-4e61-bb02-41be90c65317]...
18:16:46.853 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[f4381c47-a88b-44e9-9643-fc9af06df8a4]...
18:16:46.853 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[4886a296-15d7-4ea6-8c7a-89a03055d276]...
18:16:46.854 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[30798703-7cff-48d6-99a5-7b111139f642]...
18:16:46.854 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[f90cb36d-411b-4bc4-aff0-0929336a8810]...
18:16:46.859 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[07a14d28-7251-47dc-bb90-7f9e43de81ab]...
18:16:46.860 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[e62d63f9-ab7b-4ec3-a0ed-f5af2023a629]...
18:16:46.860 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[1cba3bd8-3047-455f-9f38-5157437ad611]...
18:16:46.860 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[dedaea30-4d95-432d-af71-2467b94d1ce1]...
18:16:46.861 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[9da6fe4c-055b-4ae2-bbce-5fb4a3c3b356]...
18:16:46.861 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[f4f90201-1963-4a5c-9251-81f6437f6777]...
18:16:46.862 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[e81b00d9-8c8a-4d0f-89fb-229a755a4572]...
18:16:46.862 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[a7d28afe-cd5f-44ab-99b3-13035b606b41]...
18:16:46.863 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[7aa37795-23a4-475d-861b-7ec0cc993d8e]...
18:16:46.863 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[f77b38a5-1bec-46b1-bc39-0a6febb95015]...
18:16:46.864 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[6421ee96-35a6-4ec9-99c2-e8da4aae07c7]...
18:16:46.864 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[600ea306-6c29-44bd-89a3-6e7060961901]...
18:16:46.871 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[f43212d0-74cb-44eb-a780-64c1a17ac0c4]...
18:16:46.872 [main] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitTemplate[36d602a9-bede-4bca-869d-e464dab3fd78]...
18:16:47.340 [pool-1-thread-83] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitConfig[syncTestRoot]...
18:16:47.362 [pool-1-thread-83] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 5% of max consistency checks passed of LocationConfigRegistry after 1 applied modifications.
18:16:47.383 [pool-1-thread-76] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register DeviceClass[syncTestDeviceClass]...
18:16:47.395 [pool-1-thread-76] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 50% of max consistency checks passed of DeviceClassRegistry after 1 applied modifications.
18:16:47.463 [pool-2-thread-7] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 100% consistency checks passed of LocationConfigRegistry after 6 applied modifications.
18:16:47.516 [pool-2-thread-5] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 100% consistency checks passed of DeviceClassRegistry after 2 applied modifications.
18:16:47.535 [pool-1-thread-98] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitConfig[syncTestDevice - 0]...
18:16:47.535 [Thread-2548] ERROR o.o.b.r.u.t.VirtualRegistrySyncTest ═══⚀ Context[rootlocation] is not available!
18:16:47.535 [Thread-2548] ERROR o.o.b.r.u.t.VirtualRegistrySyncTest =====================================
18:16:47.535 [Thread-2548] ERROR o.o.b.r.u.t.VirtualRegistrySyncTest Context[rootlocation] is not available!
org.openbase.jul.exception.NotAvailableException: Context[rootlocation] is not available!
	at org.openbase.bco.registry.location.core.LocationRegistryController.getRootLocationConfig(LocationRegistryController.java:421)
	at org.openbase.bco.registry.unit.test.VirtualRegistrySyncTest$7.run(VirtualRegistrySyncTest.java:323)
	at java.lang.Thread.run(Thread.java:748)
18:16:47.535 [Thread-2548] ERROR o.o.b.r.u.t.VirtualRegistrySyncTest =====================================
18:16:47.577 [Time-limited test] ERROR o.o.b.r.u.t.VirtualRegistrySyncTest ═╦═⚀ org.openbase.jul.exception.CouldNotPerformException: Could not register UnitConfig[syncTestDevice - 0] in DeviceConfigRegistry!
18:16:47.577 [Time-limited test] ERROR o.o.b.r.u.t.VirtualRegistrySyncTest  ╚══╦═⚀ Could not register UnitConfig[syncTestDevice - 0] in DeviceConfigRegistry!
18:16:47.577 [Time-limited test] ERROR o.o.b.r.u.t.VirtualRegistrySyncTest     ╚══╦═⚀ Could not register UnitConfig[syncTestDevice - 0] in DeviceConfigRegistrySandbox!
18:16:47.577 [Time-limited test] ERROR o.o.b.r.u.t.VirtualRegistrySyncTest        ╚══╦═⚀ Given transaction is invalid because DeviceConfigRegistrySandbox consistency check failed!
18:16:47.578 [Time-limited test] ERROR o.o.b.r.u.t.VirtualRegistrySyncTest           ╚══╦═⚀ Consistency process of DeviceConfigRegistrySandbox aborted!
18:16:47.578 [Time-limited test] ERROR o.o.b.r.u.t.VirtualRegistrySyncTest              ╚══╦═⚄ 2 errors occoured during processing!
18:16:47.580 [Time-limited test] ERROR o.o.b.r.u.t.VirtualRegistrySyncTest                 ╠══╦═⚀ Verification of Entry[UnitConfig[syncTestDevice - 0]] failed with DeviceBoundToHostConsistencyHandler!
18:16:47.580 [Time-limited test] ERROR o.o.b.r.u.t.VirtualRegistrySyncTest                 ║  ╚══╦═⚀ Entry[b55895ce-cbf8-4eb0-b2a4-63d6c6eecf82]] is not available!
18:16:47.580 [Time-limited test] ERROR o.o.b.r.u.t.VirtualRegistrySyncTest                 ║     ╚════⚀ SynchronizedRemoteRegistry[DeviceRegistryRemote[scope:/test/travis/registry/device/]][device_class] is empty!
18:16:47.582 [Time-limited test] ERROR o.o.b.r.u.t.VirtualRegistrySyncTest                 ╚══╦═⚀ Verification of Entry[UnitConfig[syncTestDevice - 0]] failed with DeviceConfigDeviceClassIdConsistencyHandler!
18:16:47.587 [Time-limited test] ERROR o.o.b.r.u.t.VirtualRegistrySyncTest                    ╚══╦═⚀ Entry[b55895ce-cbf8-4eb0-b2a4-63d6c6eecf82]] is not available!
18:16:47.587 [Time-limited test] ERROR o.o.b.r.u.t.VirtualRegistrySyncTest                       ╚════⚀ SynchronizedRemoteRegistry[DeviceRegistryRemote[scope:/test/travis/registry/device/]][device_class] is empty!
18:16:47.587 [Time-limited test] ERROR o.o.b.r.u.t.VirtualRegistrySyncTest =====================================
18:16:47.589 [Time-limited test] ERROR o.o.b.r.u.t.VirtualRegistrySyncTest org.openbase.jul.exception.CouldNotPerformException: Could not register UnitConfig[syncTestDevice - 0] in DeviceConfigRegistry!
java.util.concurrent.ExecutionException: org.openbase.jul.exception.CouldNotPerformException: Could not register UnitConfig[syncTestDevice - 0] in DeviceConfigRegistry!
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.openbase.bco.registry.unit.test.VirtualRegistrySyncTest.testVirtualRegistrySync(VirtualRegistrySyncTest.java:263)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not register UnitConfig[syncTestDevice - 0] in DeviceConfigRegistry!
	at org.openbase.jul.storage.registry.AbstractRegistry.register(AbstractRegistry.java:200)
	at org.openbase.jul.storage.registry.FileSynchronizedRegistryImpl.register(FileSynchronizedRegistryImpl.java:146)
	at org.openbase.jul.storage.registry.ProtoBufFileSynchronizedRegistry.register(ProtoBufFileSynchronizedRegistry.java:139)
	at org.openbase.bco.registry.unit.core.UnitRegistryController.lambda$registerUnitConfig$1(UnitRegistryController.java:499)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 common frames omitted
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not register UnitConfig[syncTestDevice - 0] in DeviceConfigRegistrySandbox!
	at org.openbase.jul.storage.registry.AbstractRegistry.register(AbstractRegistry.java:200)
	at org.openbase.jul.storage.registry.RegistrySandboxImpl.register(RegistrySandboxImpl.java:74)
	at org.openbase.jul.storage.registry.AbstractRegistry.register(AbstractRegistry.java:191)
	... 7 common frames omitted
Caused by: org.openbase.jul.exception.CouldNotPerformException: Given transaction is invalid because DeviceConfigRegistrySandbox consistency check failed!
	at org.openbase.jul.storage.registry.RegistrySandboxImpl.finishTransaction(RegistrySandboxImpl.java:97)
	at org.openbase.jul.storage.registry.AbstractRegistry.register(AbstractRegistry.java:194)
	... 9 common frames omitted
Caused by: org.openbase.jul.exception.CouldNotPerformException: Consistency process of DeviceConfigRegistrySandbox aborted!
	at org.openbase.jul.storage.registry.AbstractRegistry.checkConsistency(AbstractRegistry.java:866)
	at org.openbase.jul.storage.registry.RegistrySandboxImpl.finishTransaction(RegistrySandboxImpl.java:95)
	... 10 common frames omitted
Caused by: org.openbase.jul.exception.MultiException: 2 errors occoured during processing!
	at org.openbase.jul.exception.MultiException.checkAndThrow(MultiException.java:62)
	at org.openbase.jul.storage.registry.AbstractRegistry.checkConsistency(AbstractRegistry.java:774)
	... 11 common frames omitted
Caused by: org.openbase.jul.exception.VerificationFailedException: Verification of Entry[UnitConfig[syncTestDevice - 0]] failed with DeviceBoundToHostConsistencyHandler!
	at org.openbase.jul.storage.registry.AbstractRegistry.checkConsistency(AbstractRegistry.java:811)
	... 11 common frames omitted
Caused by: org.openbase.jul.exception.NotAvailableException: Entry[b55895ce-cbf8-4eb0-b2a4-63d6c6eecf82]] is not available!
	at org.openbase.jul.storage.registry.AbstractRegistry.get(AbstractRegistry.java:351)
	at org.openbase.bco.registry.unit.core.consistency.deviceconfig.DeviceBoundToHostConsistencyHandler.processData(DeviceBoundToHostConsistencyHandler.java:52)
	at org.openbase.bco.registry.unit.core.consistency.deviceconfig.DeviceBoundToHostConsistencyHandler.processData(DeviceBoundToHostConsistencyHandler.java:39)
	at org.openbase.jul.storage.registry.AbstractRegistry.checkConsistency(AbstractRegistry.java:808)
	... 11 common frames omitted
Caused by: org.openbase.jul.exception.InvalidStateException: SynchronizedRemoteRegistry[DeviceRegistryRemote[scope:/test/travis/registry/device/]][device_class] is empty!
	... 15 common frames omitted
18:16:47.589 [Time-limited test] ERROR o.o.b.r.u.t.VirtualRegistrySyncTest =====================================
18:16:47.693 [Thread-2362] INFO  o.o.b.r.u.r.UnitRegistryRemote Remote connection to Controller[/test/travis/registry/unit/] was detached because the controller shutdown was initiated.
18:16:47.799 [Thread-2363] INFO  o.o.b.r.d.r.DeviceRegistryRemote Remote connection to Controller[/test/travis/registry/device/] was detached because the controller shutdown was initiated.
18:16:47.840 [Thread-2366] INFO  o.o.b.r.a.r.AppRegistryRemote Remote connection to Controller[/test/travis/registry/app/] was detached because the controller shutdown was initiated.
18:16:47.867 [Thread-2367] INFO  o.o.b.r.a.r.AgentRegistryRemote Remote connection to Controller[/test/travis/registry/agent/] was detached because the controller shutdown was initiated.
</pre>

**Comment by pLeminoq** [comment]
Is this still needed? The root location is now registered using a plugin and with release scrab the virtual registries shall be removed.

**Comment by pLeminoq** [comment]
Should be fixed since the implementation of SynchronizationFutures around commit fef1132bdd35670130e06f76036a000f39481a97.
