### ISSUE TITLE
Sometimes the "applyAction" button does not hide again.

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.registry#57]
If entries are modified but the consistency checks are removing this modifications e.g. because of the boundToUnitHost flag, than the registry-editor receives the same unitConfig again but the update is ignored.

The apply action and the progress bar should be removed if the registry "update" method returns.

**Comment by pLeminoq** [comment]
Moved this issue to the ones for the registry editor: openbase/bco.registry.editor#33
