### ISSUE TITLE
Creating a UnitGroup without member ids

### ISSUE THREAD

**Issue by THuppke** [openbase/bco.registry#64]
This is also relevant in combination with the registry editor:

When creating a unit group in the editor, there is no complaint if no member ids are specified.
However, the following error message is shown in the bco log:
16:06:09.621 [Thread-15] ERROR o.o.j.s.RecurrenceEventFilter ═╦═⚀ Entry registry sync failed!
16:06:09.621 [Thread-15] ERROR o.o.j.s.RecurrenceEventFilter  ╚══╦═⚄ Could not sync all entries!
16:06:09.621 [Thread-15] ERROR o.o.j.s.RecurrenceEventFilter     ╚══╦═⚄ Could not register 1 entries!
16:06:09.621 [Thread-15] ERROR o.o.j.s.RecurrenceEventFilter        ╚══╦═⚀ Could not instantiate UnitGroupFactoryImpl[52248d62-3b44-47b8-8661-d164ea0bb6ed]!
16:06:09.621 [Thread-15] ERROR o.o.j.s.RecurrenceEventFilter           ╚══╦═⚀ Could not initialize class unitgroup.UnitGroupControllerImpl!
16:06:09.621 [Thread-15] ERROR o.o.j.s.RecurrenceEventFilter              ╚════⚀ UnitGroupConfig has no unit members!
16:06:09.621 [Thread-15] ERROR o.o.j.s.RecurrenceEventFilter =====================================

**Comment by pLeminoq** [comment]
This has nothing to do with the registry but with the manager, that creates controller for unitGroups, which is currently the location manager. There was a check which prevented initialization of the controller if the unit group had no members. I think this test does not need to be there so I removed it. I did the same of the UnitGroupRemote.
This has been done in commits:
* openbase/bco.dal@6451dce158bf73fc82208733bffd26794852439d
* openbase/bco.manager@b991cf147547c4c0c3159a917229d8310989d15b
