### ISSUE TITLE
Changes on device classes should also trigger the consistency checks for UnitGroups

### ISSUE THREAD

**Issue by THuppke** [openbase/bco.registry#65]
The UnitGroup BoundingBox is build up of its members' bounding boxes which may be the one forwarded from the device class. (This is introduced in commit c18ed028be5ec610f4a7d6e7dcae889f81002957). Thus the consistency checks have to be run on a change.

**Comment by pLeminoq** [comment]
Since commit b3d99f7a344d63a9dcf31253f6ec1d5bc7892671 the unit group registry directly depends on the device class registry and thus the consistency check is triggered as described above.
