### ISSUE TITLE
UserRegistry blocking sync

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.registry#67]
waitForData causes to block forever if it is called on a downstream registry like the userRegitry before the upstream unitRegitry has its data.

**Comment by DivineThreepwood** [comment]
@pLeminoq is this issue still not fixed?

**Comment by DivineThreepwood** [comment]
Any updates on this issue?

**Comment by pLeminoq** [comment]
I just tested this and I think it is fixed. If not reopen again.
