### ISSUE TITLE
Implement "remove location" plugin to improve the unit registry

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.registry#70]
In some cases location units can not be removed without dealing with registry inconsistencies.

Tasks to solve within this issue:
1. Implement UnitTests to check if inconsistencies are the result of removing randomly all locations step by step.
2. Implement Location Plugin to fix the issue
3. Check if the Implement test is successful after applying the changes.

**Comment by pLeminoq** [comment]
Plugin and test have been implemented in commit 00b08e9bc84bd5a09400ecd8fb3d13f039492379.
Additionally commit openbase/jul@d4e65ca6fa70c7da2d84b351dfd39ceb9d1eabca is required for it to work properly.
