### ISSUE TITLE
Read only flags seem to be published incorrectly

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.registry#71]
I had a look at issue openbase/bco.registry.editor#28. A debug print showed that even though bco has been started in read only mode all of the unit registry remotes said that they were not in read only mode.

**Comment by pLeminoq** [comment]
The error was that the unit registry did not notify at all and thus the read only flag would only have been synchronized if the remote requested the current data. The UnitRegistryController uses the notifyChange method from the AbstractRegistryController. This method skips the notification if at least one internal registry is still busy. The Problem with this approach is that the registry may be busy but does not produce any changes. Thus the whole notification has been skipped. In commit:

* 89e4b624a2edcc4de4389151059690618b6d0813

a task is scheduled if the notification is skipped which triggers a notification as soon as all internal registries are ready.

**Comment by pLeminoq** [comment]
Added another commit 807fe7c83070b117c34ca1f081bbfa955b20ed33 that should prevent repeated notifications.

**Comment by DivineThreepwood** [comment]
Outdated and solved.
