### ISSUE TITLE
Units can not be removed anymore

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.registry#8]
If devices are removed the units introduced by this device are not deleted which result in an inconsistent dal-unit-registry.

**Comment by pLeminoq** [comment]
Is not fixed!

**Comment by DivineThreepwood** [comment]
I don't get it. Is the issue fixed or not? :D

**Comment by pLeminoq** [comment]
Should be fixed by commit 0bab39c27a2b848be60865c524792b4a9502eae9 which also added a unit test for this problem.
