### ISSUE TITLE
UnitRegistry early shutdown failure

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.registry#84]
After introducing core launcher it can happen that registries are interrupted and shutdown during startup. Currently this does not work well with the unit registry and it will not stop.

**Comment by DivineThreepwood** [comment]
outdated.

**Comment by DivineThreepwood** [comment]
There is still a workaround implemented.
Therefor the issue is maybe still not fixed.
Workaround was been removed, let's see if it occurs again.

**Comment by DivineThreepwood** [comment]
Did not occur again... seems to be fixed.
