### ISSUE TITLE
All core registries (template & class) should be initially auto downloaded

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.registry#88]
To optimize the initial bco start, the discussed  registries should be auto downloaded via java property defined git repo refs. Additionally, the implementation need to take care about downloading the most latest and compatible version of available database. This e.g. can be archived via git database tags encoding the version. The compatible version can than be detected via the latest database converter provided by the executing code base.

**Comment by pLeminoq** [comment]
Duplicated in #101
