### ISSUE TITLE
DeviceConfig -> UnitIDs are not synchronized

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.registry#9]
If dal-units are registered and linked to unit hosts but the unit host does not know these units, they are re generated which results in duplicated unit labels per location.

2 Issues to Fix:
* If devices are configured and those devices directly marked as NON Installed  /Disabled the dal units introduced by this device are registered and linked to the unithost but the unit Id List of the device config is not filled.
* A consistency handler is needed to relink exists dal units to there devices.

**Comment by pLeminoq** [comment]
I just tested the first issue and cannot reproduce it. Even when registering a device and marking it directly as disabled and non installed its unit id list is still filled correctly.
If this issue it not there anymore is a consistency handler still needed?

**Comment by DivineThreepwood** [comment]
Issue is outdated.
