### ISSUE TITLE
Unit registry does not guarantee updated remote registries after register/update.

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.registry#98]
This bug has deep impact on many registry synchronization tasks!

* revert workaround in jul after fixing this issue!
  * `git revert 5c6a9a00`

**Comment by DivineThreepwood** [comment]
The issue is now logged if it occurs during unit registration in the mock registry. ff62a9c2

**Comment by pLeminoq** [comment]
Issue is tested in a unit test and fixed with commit openbase/jul@422e6bb0793ccaad832de5025cc00a4a7d2705db.
The problem was that the sync future could return before the internal prioritized observable, that updates internal remote registries, was finished.

**Comment by DivineThreepwood** [comment]
Fix already confirmed.
